name: Deploy branch

description: Deploy branch to gh-pages branch

inputs:
  branch-name:
    description: "Branch name"
    default: "main"

runs:
  using: "composite"
  steps:
    - name: Print branch name
      run: echo ${{ github.event.pull_request }}
      shell: bash
    - name: Print etwas
      run: echo "${{ github.head_ref }}"
      shell: bash

    # - name: Use Node.js 16
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: 16
    # - name: Echo context
    #   run: echo
# jobs:
#   deploy-branch:
#     runs:
#       # using: "composite"
#       steps:
#         - name: Checkout
#           uses: actions/checkout@v2
# - name: Print
#   run: echo 'DO somethiong'
# - name: Use Node.js 16
#   uses: actions/setup-node@v3
# - name: Print
#   run: echo 'Running using composite'
