name: Deploy to github pages on push to main

on:
  pull_request:
    types: [opened]

jobs:
  create-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Print
        run: branch_name=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p') && echo $branch_name
