name: Deploy branch to gh-pages branch

on:
  push:
    branches: [main]

jobs:
  deploy-branch:
    runs-on: ubuntu-20.04
    env:
      TARGET_BRANCH: gh-pages
      BUILD_DIR: build
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          always-auth: true
          registry-url: "https://npm.pkg.github.com"
          scope: "@oviva-ag"
      - name: Fetch
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git config --global user.name 'danielgrieb-oviva'
          git config --global user.email 'danielgrieb@oviva.com'
          git fetch
      - name: Update gh-pages branch with new build
        run: |
          npm install --silent
          npm run build --silent
          git switch --force ${TARGET_BRANCH}
          git add ./${BUILD_DIR}
          git stash --keep-index -u
          find ./ -maxdepth 1 -type f -delete
          rm -rf ./static
          mv ./${BUILD_DIR}/* ./
          rm -rf ./${BUILD_DIR}
      - name: Push changes
        run: |
          git add .
          git diff-index --quiet HEAD || git commit -am "deploy static files"
          git push --force origin ${TARGET_BRANCH}
