name: Deploy branch to gh-pages branch

on:
  push:
    branches: [main]
  pull_request:

jobs:
  deploy-branch:
    runs-on: ubuntu-18.04
    env:
      TARGET_BRANCH: gh-pages
      BUILD_DIR: build

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Set branch name
        run: |
          echo "TICKET_NAME=$(git branch --show-current | sed -r 's/^.*\/(.*)$/\1/')" >> ${GITHUB_ENV}
      - name: Fetch
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git config --global user.name 'danielgrieb-oviva'
          git config --global user.email 'danielgrieb@oviva.com'
          git fetch
      - name: Update TARGET_BRANCH with new build
        run: |
          npm install --silent
          npm run build --silent
          cp -r ${BUILD_DIR} ~/${BUILD_DIR}
          git stash && git checkout ${TARGET_BRANCH}
          rm -rf ./${TICKET_NAME}
          mv ~/${BUILD_DIR} ./${TICKET_NAME}
      - name: Update open-pr list
        # if: ${{ github.event.pull_request.opened  == 'true' && $BRANCH_NAME != 'main' }}
        run: |
          mkdir -p ./open-pull-requests
          touch ./open-pull-requests/index.html
          echo "<a href="http://oviva-ag.github.io/${GITHUB_REPOSITORY}/${TICKET_NAME}">${TICKET_NAME}</a>" >> ./open-pull-requests/index.html
      - name: Push changes
        run: |
          git status
          git add ./${BUILD_DIR}/* ./open-pull-requests/index.html && git commit -m "Deployed build"
          git push origin ${TARGET_BRANCH}
